FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
  
  # Copy requirements.txt to the container
COPY requirements.txt /app/
  
  # Install system dependencies and Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/
  
  # Collect static files
RUN python manage.py collectstatic --noinput
  
  # Run migrations
  #RUN python manage.py makemigrations && python manage.py migrate
  
  # Set environment variable for PATH
ENV PATH="/usr/local/bin:$PATH"
  
  # Run the development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
