services:
  backend:
    image: backed_image_name:0.0.1
    restart: unless-stopped
    container_name: prod-backend
    volumes:
      - prod_static_volume:/app/static
      - prod_media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CACHE_BACKEND_URL: redis://:${REDIS_PASSWORD}@redis:6379/1
      DOMAIN: ${BACKEND_DOMAIN}
    networks:
      - app-network
      - shared-network
    labels:
      traefik.enable: "true"
      traefik.http.routers.prod-web.rule: "Host(`${BACKEND_DOMAIN}`)"
      traefik.http.routers.prod-web.entrypoints: "websecure"
      traefik.http.routers.prod-web.tls.certresolver: "le"
      traefik.http.services.prod-web.loadbalancer.server.port: "8000"
      traefik.http.services.prod-web.loadbalancer.sticky: "true"
      traefik.docker.network: "shared-network"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: prod-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: prod-redis
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "${REDIS_PASSWORD}",
      "--maxmemory", "256mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - prod_static_volume:/usr/share/nginx/html/static:ro
      - prod_media_volume:/usr/share/nginx/html/media:ro
      - ./logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started
    labels:
      traefik.enable: "true"
      traefik.http.routers.prod-staticfiles.rule: "Host(`${CDN_DOMAIN}`)"
      traefik.http.routers.prod-staticfiles.entrypoints: "websecure"
      traefik.http.routers.prod-staticfiles.tls.certresolver: "le"
      traefik.http.services.prod-staticfiles.loadbalancer.server.port: "80"
      traefik.http.middlewares.static-compress.compress: "true"
      traefik.http.routers.prod-staticfiles.middlewares: "static-compress"
      traefik.docker.network: "shared-network"

  db_backup:
    image: ganiyevuz/postgres-backup-telegram
    container_name: prod-db-backup
    volumes:
      - prod_postgres_backup:/backup
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # Override prometheus settings for production environment
  prometheus:
    container_name: prod-prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=90d'
    ports:
      - "${PROMETHEUS_PORT:-9091}:9090"
    networks:
      - app-network
      - shared-network
    environment:
      - ENVIRONMENT=prod

  # Override grafana settings for production environment
  grafana:
    container_name: prod-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-StrongP@ssw0rd!Change_Me}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: "${GRAFANA_DOMAIN}"
      GF_SERVER_ROOT_URL: "https://${GRAFANA_DOMAIN}"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-piechart-panel,grafana-worldmap-panel,grafana-kubernetes-app"
    networks:
      - app-network
      - shared-network
    labels:
      traefik.enable: "true"
      traefik.http.routers.prod-grafana.rule: "Host(`${GRAFANA_DOMAIN}`)"
      traefik.http.routers.prod-grafana.entrypoints: "websecure"
      traefik.http.routers.prod-grafana.tls.certresolver: "le"
      traefik.http.services.prod-grafana.loadbalancer.server.port: "3000"

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  prod_static_volume:
    driver: local
    driver_opts:
      type: none
      device: /var/www/prod/static
      o: bind
  prod_media_volume:
    driver: local
    driver_opts:
      type: none
      device: /var/www/prod/media
      o: bind
  prod_postgres_backup:

networks:
  app-network:
    driver: bridge
  shared-network:
    external: true
    name: shared-network