scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'dev-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['dev-backend:8000']

  - job_name: 'dev-userbot'
    metrics_path: /metrics
    static_configs:
      - targets: ['dev-userbot:8000']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['dev-grafana:3000']
